// app/layout.js

import React from 'react';
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Providers } from '@/lib/Providers';
import Footer from '@/components/Home/Footer';
import UserContext from '@/components/Context/UserContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tertiary Knit and Colour",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
    <html lang="en">

      <body className={inter.className}>
        <Navbar />
        <main className="">
          {children}
        </main>
      </body>

    </html>
    </Providers>
  );
}
